#version 460

#extension GL_GOOGLE_include_directive : require

// Final draw instance ID packing into flat array for easy visibility buffer access.

#include "../include/common.glsl"
#include "../include/barycentric.glsl"
#include "../include/visbuffer.glsl"

layout(local_size_x = 256) in;

layout(push_constant) uniform PlacePush
{
	uint streamSlot;
} pc;

void main()
{
	uint i     = gl_GlobalInvocationID.x;
	uint count = getIndirectDispatchBuffer().args[pc.streamSlot].w;
	if (i >= count) return;

	StreamEntry e = getInstanceStreamsBuffer().entries[pc.streamSlot * MAX_INSTANCES_PER_STREAM + i];

	uint binID  = streamBinID(e.binID);
	uint lodIdx = streamLODIndex(e.binID);

	uint flatIdx = pc.streamSlot * MAX_DRAW_BINS + binID;
	uint intra   = atomicAdd(getDrawBinCounterBuffer().drawBinCounters[flatIdx], 1u);
	uint base    = getDrawBinBuffer().drawBins[flatIdx].instanceOffset;

	uint instanceID = getVisibleInstanceBuffer().visibles[e.visibleID].instanceID;

	getDrawInstanceIDsBuffer().ids[streamInstanceBase(pc.streamSlot) + base + intra] = packVisID(instanceID, lodIdx);
}
