#version 460

#extension GL_GOOGLE_include_directive    : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/clustered.glsl"
#include "../include/common.glsl"

layout(local_size_x = 1) in;

void main()
{
	if (gl_GlobalInvocationID.x != 0u) return;

	DispatchIndirectArgsBuffer dispatchArgs = getIndirectDispatchBuffer();

	ClusteredData clustered = getClusteredData();

	const uint visibleCount = getVisibleLightCountBuffer().count;
	const uint clusterCount = clusteredData.clusterCount;

	// Run next passes over clusters or over lights?
	// Using during cluster counts to figure out how many lights are in clusters
	// and final cluster id assignment pass.
	uint workItemCount = (visibleCount <= LIGHT_THRESHOLD) ? clusterCount : visibleCount;
	uint groupCountX = (workItemCount + 255u) / 256u;
	dispatchArgs.args[INDIRECT_DISPATCH_SLOT_LIGHTS] = uvec4(groupCountX, 1u, 1u, 0u);

	// Only needed for offset scan pass
	uint clusterGroups = (clusterCount + 255u) / 256u;
	dispatchArgs.args[INDIRECT_DISPATCH_SLOT_CLUSTERS] = uvec4(clusterGroups, 1u, 1u, 0u);
}
