#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D transparentAccum;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D transparentRevealage;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_3) uniform sampler2D atmosphereHDR;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_4) uniform sampler2D sceneDepth;

layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1, rgba16f) uniform image2D hdrSceneComposite;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 dim   = imageSize(hdrSceneComposite);
	if (any(greaterThanEqual(coord, dim))) return;

	float depth = texelFetch(sceneDepth, coord, 0).r;

	vec4 current;
	if (depth == 0.0)
		current = vec4(texelFetch(atmosphereHDR, coord, 0).rgb, 1.0);
	else
		current = imageLoad(hdrSceneComposite, coord);

	float reveal = clamp(texelFetch(transparentRevealage, coord, 0).r, 0.0, 1.0);

	if (reveal < 0.9999)
	{
		vec4 accum = texelFetch(transparentAccum, coord, 0);

		vec3 transparentColor = accum.rgb / max(accum.a, 1e-5);

		current.rgb = transparentColor * (1.0 - reveal) + current.rgb * reveal;
		current.a *= reveal;
	}

	imageStore(hdrSceneComposite, coord, current);
}