#version 460

#extension GL_GOOGLE_include_directive    : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/common.glsl"

layout(local_size_x = 64) in;

const int WAVE_SIZE = 64;
const int SAMPLE_COUNT = 60;
const int HARD_SHADOW_SAMPLES = 4;
const int FADE_OUT_SAMPLES = 8;
const int READ_COUNT = (SAMPLE_COUNT / WAVE_SIZE + 2);
const int DEPTH_BOUNDS_MIN = 0;
const int DEPTH_BOUNDS_MAX = 1;
const int NEAR_DEPTH_VALUE = 1;
const int FAR_DEPTH_VALUE = 0;

// Screen space contact shadows based off bend studios code.
// https://www.bendstudio.com/blog/inside-bend-screen-space-shadows/

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D inDepth;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D outShadowMask;

layout(push_constant) uniform SSSPush {
	vec4 lightCoords;
	ivec2 waveOffsets;
	vec2 invDepthSize;
	float surfaceThickness;
	float bilinearThreshold;
	float shadowContrast;
} pc;

void ComputeWaveExtents(
	ivec3 inGroupID,
	uint inGroupThreadID,
	out vec2 outDeltaXY,
	out vec2 outPixelXY,
	out float outPixelDistance,
	out bool outMajorAxisX) {

	ivec2 xy = inGroupID.yz * WAVE_SIZE + pc.waveOffsets.xy;

	// integer light position / fractional component
	vec2 light_xy = floor(pc.lightCoords.xy) + 0.5;
	vec2 light_xy_fraction = pc.lightCoords.xy - light_xy;
	bool reverse_direction = pc.lightCoords.w > 0.0;

	ivec2 sign_xy = sign(xy);
	bool horizontal = abs(xy.x + sign_xy.y) < abs(xy.y - sign_xy.x);

	ivec2 axis;
	axis.x = horizontal ? (+sign_xy.y) : (0);
	axis.y = horizontal ? (0) : (-sign_xy.x);

	// Apply wave offset
	xy = axis * inGroupID.x + xy;
	vec2 xy_f = vec2(xy);

	// For interpolation to the light center, we only really care about the larger of the two axis
	bool x_axis_major = abs(xy_f.x) > abs(xy_f.y);
	float major_axis = x_axis_major ? xy_f.x : xy_f.y;

	float major_axis_start = abs(major_axis);
	float major_axis_end = abs(major_axis) - float(WAVE_SIZE);

	float ma_light_frac = x_axis_major ? light_xy_fraction.x : light_xy_fraction.y;
	ma_light_frac = major_axis > 0.0 ? -ma_light_frac : ma_light_frac;

	// back in to screen direction
	vec2 start_xy = xy_f + light_xy;

	// For the very inner most ring, we need to interpolate to a pixel centered UV, so the UV->pixel rounding doesn't skip output pixels
	vec2 end_xy = mix(pc.lightCoords.xy, start_xy, (major_axis_end + ma_light_frac) / (major_axis_start + ma_light_frac));

	// The major axis should be a round number
	vec2 xy_delta = (start_xy - end_xy);

	// Inverse the read order when reverse direction is true
	float thread_step = float(inGroupThreadID ^ (reverse_direction ? 0u : (WAVE_SIZE - 1u)));

	vec2 pixel_xy = mix(start_xy, end_xy, thread_step / float(WAVE_SIZE));
	float pixel_distance = major_axis_start - thread_step + ma_light_frac;

	outPixelXY = pixel_xy;
	outPixelDistance = pixel_distance;
	outDeltaXY = xy_delta;
	outMajorAxisX = x_axis_major;
}

shared float DepthData[READ_COUNT * WAVE_SIZE];

void main()
{
	vec2 xy_delta;
	vec2 pixel_xy;
	float pixel_distance;
	bool x_axis_major;

	ComputeWaveExtents(
		ivec3(gl_WorkGroupID),
		gl_LocalInvocationID.x,
		xy_delta,
		pixel_xy,
		pixel_distance,
		x_axis_major
	);

	// Read in the depth values
	float sampling_depth[READ_COUNT];
	float shadowing_depth[READ_COUNT];
	float depth_thickness_scale[READ_COUNT];
	float sample_distance[READ_COUNT];

	const float direction = -pc.lightCoords.w;
	const float z_sign = NEAR_DEPTH_VALUE > FAR_DEPTH_VALUE ? -1 : +1;

	int i;
	bool skip_pixel = false;
	vec2 write_xy = floor(pixel_xy);

	SceneData scene = getSceneData();

	// Vulkan flip
	write_xy.y = scene.renderExtentSize.y - write_xy.y;

	vec2 fullTexelSize = pc.invDepthSize; // 1/fullscreensize

	for (i = 0; i < READ_COUNT; i++) {
		// We sample depth twice per pixel per sample, and interpolate with an edge detect filter
		// Interpolation should only occur on the minor axis of the ray - major axis coordinates should be at pixel centers
		vec2 read_xy = floor(pixel_xy);
		float minor_axis = x_axis_major ? pixel_xy.y : pixel_xy.x;

		float bilinear = fract(minor_axis) - 0.5;
		vec2 depths;

		int bias = (bilinear > 0.0) ? 1 : -1;
		vec2 offset_xy = vec2(x_axis_major ? 0 : bias, x_axis_major ? bias : 0);

		read_xy += 0.5;

		// Sample at pixel centers
		vec2 read_xy_one = read_xy * fullTexelSize;
		read_xy_one.y = 1.0 - read_xy_one.y;
		vec2 read_xy_two = (read_xy + offset_xy) * fullTexelSize;
		read_xy_two.y = 1.0 - read_xy_two.y;
		depths.x = textureLod(inDepth, read_xy_one, 0).r;
		depths.y = textureLod(inDepth, read_xy_two, 0).r;

		// Depth thresholds (bilinear/shadow thickness) are based on a fractional ratio of the difference between sampled depth and the far clip depth
		depth_thickness_scale[i] = abs(FAR_DEPTH_VALUE - depths.x);

		// If depth variance is more than a specific threshold, then just use point filtering
		bool use_point_filter = abs(depths.x - depths.y) > depth_thickness_scale[i] * pc.bilinearThreshold;

		// The pixel starts sampling at this depth
		sampling_depth[i] = depths.x;

		// Early out gate
		if (i == 0) {
			skip_pixel = (sampling_depth[0] >= DEPTH_BOUNDS_MAX) || (sampling_depth[0] <= DEPTH_BOUNDS_MIN);
		}

		float edge_depth = depths.x;
		// Any sample in this wavefront is possibly interpolated towards the bilinear sample
		// So use should use a shadowing depth that is further away, based on the difference between the two samples
		float shadow_depth = depths.x + abs(depths.x - depths.y) * z_sign;

		// Shadows cast from this depth
		shadowing_depth[i] = use_point_filter ? edge_depth : shadow_depth;

		// Store for later
		sample_distance[i] = pixel_distance + (WAVE_SIZE * i) * direction;

		// Iterate to the next pixel along the ray. This will be WAVE_SIZE pixels along the ray...
		pixel_xy += xy_delta * direction;
	}


	// Write the shadow depths to LDS
	for (i = 0; i < READ_COUNT; i++) {
		// Perspective correct the shadowing depth, in this space, all light rays are parallel
		float stored_depth = (shadowing_depth[i] - pc.lightCoords.z) / sample_distance[i];

		if (i != 0)
		{
			// For pixels within sampling distance of the light, it is possible that sampling will
			// overshoot the light coordinate for extended reads. We want to ignore these samples
			stored_depth = sample_distance[i] > 0 ? stored_depth : 1e10;
		}

		// Store the depth values in groupshared
		int idx = (i * WAVE_SIZE) + int(gl_LocalInvocationID.x);
		DepthData[idx] = stored_depth;
	}

	// Sync wavesfront now shared DepthData is written
	memoryBarrierShared();
	barrier();

	// If the starting depth isn't in depth bounds, then we don't need a shadow
	if (skip_pixel) return;

	float start_depth = sampling_depth[0];

	//// far depth precision offset
	//start_depth = mix(start_depth, FAR_DEPTH_VALUE, -1.0 / 65535.0);

	// perspective correct the depth
	start_depth = (start_depth - pc.lightCoords.z) / sample_distance[0];

	// Start by reading the next value
	int sample_index = int(gl_LocalInvocationID.x) + 1;

	vec4 shadow_value = vec4(1.0);
	float hard_shadow = 1.0;

	// This is the inverse of how large the shadowing window is for the projected sample data.
	// All values in the LDS sample list are scaled by 1.0 / sample_distance, such that all light directions become parallel.
	// The multiply by sample_distance[0] here is to compensate for the projection divide in the data.
	// The 1.0 / pc.surfaceThickness is to adjust user selected thickness. So a 0.5% thickness will scale depth values from [0,1] to [0,200]. The shadow window is always 1 wide.
	// 1.0 / depth_thickness_scale[0] is because SurfaceThickness is percentage of remaining depth between the sample and the far clip - not a percentage of the full depth range.
	// The min() function is to make sure the window is a minimum width when very close to the light. The +direction term will bias the result so the pixel at the very center of the light is either fully lit or shadowed
	float depth_scale = min(sample_distance[0] + direction, 1.0 / pc.surfaceThickness) * sample_distance[0] / depth_thickness_scale[0];

	start_depth = start_depth * depth_scale - z_sign;

	// The first number of hard shadow samples, a single pixel can produce a full shadow
	for (i = 0; i < HARD_SHADOW_SAMPLES; i++) {
		float depth_delta = abs(start_depth - DepthData[sample_index + i] * depth_scale);

		// We want to find the distance of the sample that is closest to the reference depth
		hard_shadow = min(hard_shadow, depth_delta);
	}

	// Brute force go!
	// The main shadow samples, averaged in to a set of 4 shadow values
	for (i = HARD_SHADOW_SAMPLES; i < SAMPLE_COUNT - FADE_OUT_SAMPLES; i++) {
		float depth_delta = abs(start_depth - DepthData[sample_index + i] * depth_scale);

		// Do the same as the hard_shadow code above, but this will accumulate to 4 separate values.
		// By using 4 values, the average shadow can be taken, which can help soften single-pixel shadows.
		shadow_value[i & 3] = min(shadow_value[i & 3], depth_delta);
	}

	// Final fade out samples
	for (i = SAMPLE_COUNT - FADE_OUT_SAMPLES; i < SAMPLE_COUNT; i++) {
		float depth_delta = abs(start_depth - DepthData[sample_index + i] * depth_scale);

		// Add the fade value to these samples
		const float fade_out = float(i + 1 - (SAMPLE_COUNT - FADE_OUT_SAMPLES)) / float(FADE_OUT_SAMPLES + 1) * 0.75;

		shadow_value[i & 3] = min(shadow_value[i & 3], depth_delta + fade_out);
	}

	// Apply the contrast value.
	// A value of 0 indicates a sample was exactly matched to the reference depth (and the result is fully shadowed)
	// We want some boost to this range, so samples don't have to exactly match to produce a full shadow.
	shadow_value = saturate(shadow_value * (pc.shadowContrast) + (1 - pc.shadowContrast));
	hard_shadow = saturate(hard_shadow * (pc.shadowContrast) + (1 - pc.shadowContrast));

	float result = 0.0;

	// Take the average of 4 samples, this is useful to reduces aliasing noise in the source depth, especially with long shadows.
	result = dot(shadow_value, vec4(0.25));

	// If the first samples are always producing a hard shadow, then compute this value separately.
	result = min(hard_shadow, result);

	imageStore(outShadowMask, ivec2(write_xy), vec4(result, 0.0, 0.0, 1.0));
}
