#version 460

#extension GL_ARB_separate_shader_objects : require
#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"

// Amazing resource on why exposure is important
// https://bruop.github.io/exposure/

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D hdrScene;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D sceneDepth;

shared vec2 localLuminance[gl_WorkGroupSize.x * gl_WorkGroupSize.y];

const float LUM_EPSILON = 1e-4;

void main()
{
	ivec2 size  = textureSize(hdrScene, 0);
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	uint  lid   = gl_LocalInvocationIndex;

	float invPreExposure = 1.0 / getPreExposure();

	float logY = 0.0;
	float weight = 0.0;

	if (coord.x < size.x && coord.y < size.y)
	{
		float depth = texelFetch(sceneDepth, coord, 0).r;

		if (depth > 0.0)
		{
			vec3 hdr = sanitizeHDR(
				texelFetch(hdrScene, coord, 0).rgb, COLOR_HISTORY_MAX);

			float Y = max(dot(hdr, vec3(0.2126, 0.7152, 0.0722)), 0.0)
				* invPreExposure;

			logY = log(Y + LUM_EPSILON);
			weight = 1.0;
		}
	}

	localLuminance[lid] = vec2(logY, weight);
	barrier();

	for (uint stride = (gl_WorkGroupSize.x * gl_WorkGroupSize.y) >> 1; stride > 0; stride >>= 1) {
		if (lid < stride)
			localLuminance[lid] += localLuminance[lid + stride];
		barrier();
	}

	if (lid == 0) {
		uint groupIndex = gl_WorkGroupID.y * gl_NumWorkGroups.x + gl_WorkGroupID.x;
		getLuminanceBuffer().luminanceSums[groupIndex + 1u] = vec4(localLuminance[0], 0.0, 0.0);
	}
}