#version 460

#extension GL_ARB_separate_shader_objects : require
#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"

const float SKY_MAX_NITS        = 60000.0;

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D equirectImage;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2DArray skyboxStorage;

vec2 SampleSphericalMap(vec3 v) {
	vec2 invAtan = vec2(0.1591, 0.3183); // 1 / (2 * pi), 1 / pi
	vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
	uv *= invAtan;
	uv += 0.5;
	return uv;
}

layout(push_constant) uniform CubemapPush
{
	float skyScale;
} pc;

void main() {
	ivec3 storePos = ivec3(gl_GlobalInvocationID.xyz);
	ivec2 dstSize = imageSize(skyboxStorage).xy;
	if (storePos.x >= dstSize.x || storePos.y >= dstSize.y) {
		return;
	}
	vec2 uv = (vec2(storePos.xy) + 0.5) / vec2(dstSize); // Normalized coordinates
	uv = uv * 2.0 - 1.0; // Map to range [-1, 1]

	vec3 direction;
	switch (storePos.z) {
		case 0: direction = normalize(vec3(1.0,   -uv.y, -uv.x)); break; // +X
		case 1: direction = normalize(vec3(-1.0,  -uv.y,  uv.x)); break; // -X
		case 2: direction = normalize(vec3(uv.x,   1.0,   uv.y)); break; // +Y
		case 3: direction = normalize(vec3(uv.x,  -1.0,  -uv.y)); break; // -Y
		case 4: direction = normalize(vec3(uv.x,  -uv.y,  1.0));  break; // +Z
		case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0));  break; // -Z
		default: direction = vec3(0.0); break; // Should not happen
	}

	vec2 sphericalUV = SampleSphericalMap(direction);
	float lod = max(log2(float(textureSize(equirectImage, 0).x) / (4.0 * float(dstSize.x))), 0.0);
	vec4 color = textureLod(equirectImage, sphericalUV, lod);

	vec3 nits = min(color.rgb * pc.skyScale, vec3(SKY_MAX_NITS));

	imageStore(skyboxStorage, storePos, vec4(nits, color.a));
}
