#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_ARB_separate_shader_objects : require

#include "../include/common.glsl"
#include "../include/ssgi_push.glsl"

// Original XE_GTAO implementation
// https://github.com/GameTechDev/XeGTAO/blob/master/Source/Rendering/Shaders/XeGTAO.hlsli

// This denoise shader only works with taa on

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D rawAO;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D edgeInfo;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D aoFiltered;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_2, rgba8) uniform image2D bentNormals;

void addSample(float val, float edgeWeight, inout float sum, inout float sumWeight) {
	sum       += edgeWeight * val;
	sumWeight += edgeWeight;
}

void main() {
	// Dispatch working on 2x1 pixels
	const ivec2 pixCoordBase = ivec2(gl_GlobalInvocationID.xy) * ivec2(2, 1);

	SceneData scene = getSceneData();
	const ivec2 halfExtent = (ivec2(scene.renderExtentSize.xy) + 1) / 2;
	if (any(greaterThanEqual(pixCoordBase, halfExtent))) return;

	float blurAmount = (pc.isFinalPass != 0u)
		? pc.denoiseBlurBeta
		: pc.denoiseBlurBeta / 5.0;

	const float diagWeight = 0.85 * 0.5;
	const vec2 halfPixelSize = vec2(scene.renderPixelSizes.zw);
	vec2 gatherUV = vec2(pixCoordBase) * halfPixelSize;

	// Edge gathers
	vec4 edgesQ0 = textureGatherOffset(edgeInfo, gatherUV, ivec2(0, 0), 0);
	vec4 edgesQ1 = textureGatherOffset(edgeInfo, gatherUV, ivec2(2, 0), 0);
	vec4 edgesQ2 = textureGatherOffset(edgeInfo, gatherUV, ivec2(1, 2), 0);

	// AO gathers
	vec4 aoQ0 = textureGatherOffset(rawAO, gatherUV, ivec2(0, 0), 0);
	vec4 aoQ1 = textureGatherOffset(rawAO, gatherUV, ivec2(2, 0), 0);
	vec4 aoQ2 = textureGatherOffset(rawAO, gatherUV, ivec2(0, 2), 0);
	vec4 aoQ3 = textureGatherOffset(rawAO, gatherUV, ivec2(2, 2), 0);

	for (int side = 0; side < 2; side++) {
		ivec2 pixCoord = ivec2(pixCoordBase.x + side, pixCoordBase.y);
		if (pixCoord.x >= halfExtent.x) continue;

		vec4 edgesL = unpackEdges((side == 0) ? edgesQ0.x : edgesQ0.y);
		vec4 edgesT = unpackEdges((side == 0) ? edgesQ0.z : edgesQ1.w);
		vec4 edgesR = unpackEdges((side == 0) ? edgesQ1.x : edgesQ1.y);
		vec4 edgesB = unpackEdges((side == 0) ? edgesQ2.w : edgesQ2.z);
		vec4 edgesC = unpackEdges((side == 0) ? edgesQ0.y : edgesQ1.x);

		// Edges aren't perfectly symmetrical: edge detection algorithm does not guarantee that a left edge on the right pixel will match the right edge on the left pixel (although
		// they will match in majority of cases). This line further enforces the symmetricity, creating a slightly sharper blur. Works real nice with TAA.
		edgesC *= vec4(edgesL.y, edgesR.x, edgesT.w, edgesB.z);

		// this allows some small amount of AO leaking from neighbours if there are 3 or 4 edges; this reduces both spatial and temporal aliasing
		const float leakThreshold = 2.5;
		const float leakStrength  = 0.5;
		float edginess = saturate(4.0 - leakThreshold - dot(edgesC, vec4(1.0)))
						 / (4.0 - leakThreshold) * leakStrength;
		edgesC = saturate(edgesC + edginess);

		// for diagonals; used by first and second pass
		float weightTL = diagWeight * (edgesC.x * edgesL.z + edgesC.z * edgesT.x);
		float weightTR = diagWeight * (edgesC.z * edgesT.y + edgesC.y * edgesR.z);
		float weightBL = diagWeight * (edgesC.w * edgesB.x + edgesC.x * edgesL.w);
		float weightBR = diagWeight * (edgesC.y * edgesR.w + edgesC.w * edgesB.y);

		// first pass
		float aoC  = (side == 0) ? aoQ0.y : aoQ1.x;
		float aoL  = (side == 0) ? aoQ0.x : aoQ0.y;
		float aoT  = (side == 0) ? aoQ0.z : aoQ1.w;
		float aoR  = (side == 0) ? aoQ1.x : aoQ1.y;
		float aoB  = (side == 0) ? aoQ2.z : aoQ3.w;
		float aoTL = (side == 0) ? aoQ0.w : aoQ0.z;
		float aoBR = (side == 0) ? aoQ3.w : aoQ3.z;
		float aoTR = (side == 0) ? aoQ1.w : aoQ1.z;
		float aoBL = (side == 0) ? aoQ2.w : aoQ2.z;

		float sumWeight = blurAmount;
		float sum       = aoC * sumWeight;

		addSample(aoL,  edgesC.x, sum, sumWeight);
		addSample(aoR,  edgesC.y, sum, sumWeight);
		addSample(aoT,  edgesC.z, sum, sumWeight);
		addSample(aoB,  edgesC.w, sum, sumWeight);
		addSample(aoTL, weightTL, sum, sumWeight);
		addSample(aoTR, weightTR, sum, sumWeight);
		addSample(aoBL, weightBL, sum, sumWeight);
		addSample(aoBR, weightBR, sum, sumWeight);

		float result = sum / max(sumWeight, 1e-5);

		if (pc.isFinalPass == 0)
		{
			imageStore(aoFiltered, pixCoord, vec4(result));
		}
		else
		{
			vec4 bentAo = imageLoad(bentNormals, pixCoord); // Bent normals
			bentAo.a = result;
			imageStore(bentNormals, pixCoord, bentAo);
		}
	}
}
