#version 460

#extension GL_GOOGLE_include_directive : require

#include "../include/common.glsl"
#include "../include/depth.glsl"
#include "../include/ssgi_push.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D inGIHistory;
layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D inEdgeInfo;
layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1, rgba16f) writeonly uniform image2D outGI;

void main()
{
	ivec2 extent = textureSize(inGIHistory, 0);
	ivec2 p = ivec2(gl_GlobalInvocationID.xy);

	if (any(greaterThanEqual(p, extent))) return;

	vec4 c = texelFetch(inGIHistory, p, 0);
	vec4 e = unpackEdges(texelFetch(inEdgeInfo, p, 0).r);

	ivec2 offsets[4] = ivec2[4](
		ivec2(-1, 0),
		ivec2(1, 0),
		ivec2(0, -1),
		ivec2(0, 1));

	vec3 sum = c.rgb * 4.0;
	float weight = 4.0;

	for (int i = 0; i < 4; ++i)
	{
		vec4 v = texelFetch(
			inGIHistory,
			clamp(p + offsets[i], ivec2(0), extent - 1),
			0);

		float w = e[i] * v.a;

		sum += v.rgb * w;
		weight += w;
	}

	imageStore(outGI, p, vec4(sum / weight, c.a));
}