//#version 460
//
//#extension GL_GOOGLE_include_directive : require
//#extension GL_ARB_separate_shader_objects : require
//
//#include "../include/common.glsl"
//#include "../include/cmaa2.glsl"
//
//layout(local_size_x = 1) in;
//
//// https://github.com/GameTechDev/CMAA2/blob/master/Projects/CMAA2/CMAA2/CMAA2.hlsl
//
//layout(push_constant) uniform CMAA2Push {
//	uint halfWidth;
//	uint maxShapeCandidates;
//	uint maxDeferredItems;
//	uint maxDeferredLocations;
//	vec4 params; // w. 0 candidate / 1 deferred loc count
//} pc;
//
//void main()
//{
//	if (gl_GlobalInvocationID.x != 0u) return;
//
//	DispatchIndirectArgsBuffer dispatchArgs = getIndirectDispatchBuffer();
//
//	Cmaa2ControlBuffer control = getCMAA2ControlBuffer();
//
//	bool pass = bool(pc.params.w);
//
//	if (!pass)
//	{
//		uint candidateCount = control.control[CMAA2_CTRL_SHAPE_CANDIDATE_COUNT];
//
//		uint processGroupCountX =
//			(candidateCount + (CMAA2_PROCESS_CANDIDATES_NUM_THREADS - 1u)) /
//			CMAA2_PROCESS_CANDIDATES_NUM_THREADS;
//
//		dispatchArgs.args[INDIRECT_DISPATCH_SLOT_CMAA2_SHAPES] = uvec4(processGroupCountX, 1u, 1u, 0u);
//	}
//	else
//	{
//		uint deferredLocCount = control.control[CMAA2_CTRL_DEFERRED_LOCATION_COUNT];
//
//		uint deferredGroupCountX =
//			(deferredLocCount + (CMAA2_DEFERRED_APPLY_NUM_THREADS - 1u)) /
//			CMAA2_DEFERRED_APPLY_NUM_THREADS;
//
//		dispatchArgs.args[INDIRECT_DISPATCH_SLOT_CMAA2_DEFERRED] = uvec4(deferredGroupCountX, 1u, 1u, 0u);
//	}
//}
//
