//#version 460
//
//#extension GL_ARB_separate_shader_objects : require
//#extension GL_GOOGLE_include_directive : require
//
//#include "../include/common.glsl"
//
//// smaa implementation mine is based off
//// https://github.com/dmnsgn/glsl-smaa/tree/main?tab=readme-ov-file
//// https://github.com/iryoku/smaa
//
//layout(local_size_x = 16, local_size_y = 16) in;
//
//const int SMAA_MAX_SEARCH_STEPS = 16;
//const int SMAA_MAX_SEARCH_STEPS_DIAG = 8;
//const int SMAA_CORNER_ROUNDING = 25;
//
//const int SMAA_AREATEX_MAX_DISTANCE = 16;
//const int SMAA_AREATEX_MAX_DISTANCE_DIAG = 20;
//const vec2 SMAA_AREATEX_PIXEL_SIZE = vec2(1.0 / 160.0, 1.0 / 560.0);
//const float SMAA_AREATEX_SUBTEX_SIZE = (1.0 / 7.0);
//const vec2 SMAA_SEARCHTEX_SIZE = vec2(66.0, 33.0);
//const vec2 SMAA_SEARCHTEX_PACKED_SIZE = vec2(64.0, 16.0);
//const float SMAA_CORNER_ROUNDING_NORM = (float(SMAA_CORNER_ROUNDING) / 100.0);
//
//layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D inSmaaEdges;
//layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D outWeights;
//
//layout(push_constant) uniform TextureAccess {
//	uint searchTexID;
//	uint areaTexID;
//} pc;
//
//vec2 SMAASampleLevelZeroOffset(sampler2D tex, vec2 coord, vec2 offset, vec2 texelSize) {
//	return texture(tex, coord + offset * texelSize).rg;
//}
//
//vec2 SMAADecodeDiagBilinearAccess(vec2 e) {
//	e.rg = e.rg * abs(5.0 * e.rg - 5.0 * 0.75);
//	return round(e);
//}
//
//vec4 SMAADecodeDiagBilinearAccess(vec4 e) {
//	e.rb = e.rb * abs(5.0 * e.rb - 5.0 * 0.75);
//	return round(e);
//}
//
//vec2 SMAASearchDiag1(sampler2D edgesTex, vec2 texcoord, vec2 dir, vec2 texelSize, out vec2 e) {
//	vec4 coord = vec4(texcoord, -1.0, 1.0);
//	vec3 t = vec3(texelSize, 1.0);
//
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(coord.z < float(SMAA_MAX_SEARCH_STEPS_DIAG - 1) && coord.w > 0.9)) break;
//		coord.xyz = mad(t, vec3(dir, 1.0), coord.xyz);
//		e = texture(edgesTex, coord.xy).rg;
//		coord.w = dot(e, vec2(0.5, 0.5));
//	}
//	return coord.zw;
//}
//
//vec2 SMAASearchDiag2(sampler2D edgesTex, vec2 texcoord, vec2 dir, vec2 texelSize, out vec2 e) {
//	vec4 coord = vec4(texcoord, -1.0, 1.0);
//	coord.x += 0.25 * texelSize.x;
//	vec3 t = vec3(texelSize, 1.0);
//
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(coord.z < float(SMAA_MAX_SEARCH_STEPS_DIAG - 1) && coord.w > 0.9)) break;
//		coord.xyz = mad(t, vec3(dir, 1.0), coord.xyz);
//
//		// Fetch both edges at once using bilinear filtering:
//		e = texture(edgesTex, coord.xy).rg;
//		e = SMAADecodeDiagBilinearAccess(e);
//
//		coord.w = dot(e, vec2(0.5, 0.5));
//	}
//
//	return coord.zw;
//}
//
//// Similar to SMAAArea, this calculates the area corresponding to a certain
//// diagonal distance and crossing edges 'e'.
//vec2 SMAAAreaDiag(sampler2D areaTex, vec2 dist, vec2 e, float offset) {
//	vec2 texcoord = mad(vec2(SMAA_AREATEX_MAX_DISTANCE_DIAG, SMAA_AREATEX_MAX_DISTANCE_DIAG), e, dist);
//
//	// We do a scale and bias for mapping to texel space:
//	texcoord = mad(SMAA_AREATEX_PIXEL_SIZE, texcoord, 0.5 * SMAA_AREATEX_PIXEL_SIZE);
//
//	// Diagonal areas are on the second half of the texture:
//	texcoord.x += 0.5;
//
//	// Move to proper place, according to the subpixel offset:
//	texcoord.y += SMAA_AREATEX_SUBTEX_SIZE * offset;
//
//	return texture(areaTex, texcoord).rg;
//}
//
//
//// This searches for diagonal patterns and returns the corresponding weights.
//vec2 SMAACalculateDiagWeights(sampler2D edgesTex, sampler2D areaTex, vec2 texcoord, vec2 e, vec2 texelSize, vec4 subsampleIndices) {
//	vec2 weights = vec2(0.0, 0.0);
//
//	// Search for the line ends:
//	vec4 d;
//	vec2 end;
//	if (e.r > 0.0) {
//		d.xz = SMAASearchDiag1(edgesTex, texcoord, vec2(-1.0, 1.0), texelSize, end);
//		d.x += float(end.y > 0.9);
//	}
//	else {
//		d.xz = vec2(0.0, 0.0);
//	}
//	d.yw = SMAASearchDiag1(edgesTex, texcoord, vec2(1.0, -1.0), texelSize, end);
//
//	if (d.x + d.y > 2.0) { // d.x + d.y + 1 > 3
//		// Fetch the crossing edges:
//		vec4 coords = mad(vec4(-d.x + 0.25, d.x, d.y, -d.y - 0.25), vec4(texelSize, texelSize), texcoord.xyxy);
//		vec4 c;
//		c.xy = SMAASampleLevelZeroOffset(edgesTex, coords.xy, vec2(-1, 0), texelSize);
//		c.zw = SMAASampleLevelZeroOffset(edgesTex, coords.zw, vec2( 1, 0), texelSize);
//		c.yxwz = SMAADecodeDiagBilinearAccess(c.xyzw);
//
//		// Merge crossing edges at each side into a single value:
//		vec2 cc = mad(vec2(2.0, 2.0), c.xz, c.yw);
//
//		// Remove the crossing edge if we didn't found the end of the line:
//		SMAAMovc(bvec2(step(0.9, d.zw)), cc, vec2(0.0, 0.0));
//
//		// Fetch the areas for this line:
//		weights += SMAAAreaDiag(areaTex, d.xy, cc, subsampleIndices.z);
//	}
//
//	// Search for the line ends:
//	d.xz = SMAASearchDiag2(edgesTex, texcoord, vec2(-1.0, -1.0), texelSize, end);
//	if (SMAASampleLevelZeroOffset(edgesTex, texcoord, vec2(1, 0), texelSize).r > 0.0) {
//		d.yw = SMAASearchDiag2(edgesTex, texcoord, vec2(1.0, 1.0), texelSize, end);
//		d.y += float(end.y > 0.9);
//	} else {
//		d.yw = vec2(0.0, 0.0);
//	}
//
//	if (d.x + d.y > 2.0) { // d.x + d.y + 1 > 3
//		// Fetch the crossing edges:
//		vec4 coords = mad(vec4(-d.x, -d.x, d.y, d.y), vec4(texelSize, texelSize), texcoord.xyxy);
//		vec4 c;
//		c.x  = SMAASampleLevelZeroOffset(edgesTex, coords.xy, vec2(-1, 0), texelSize).g;
//		c.y  = SMAASampleLevelZeroOffset(edgesTex, coords.xy, vec2( 0,-1), texelSize).r;
//		c.zw = SMAASampleLevelZeroOffset(edgesTex, coords.zw, vec2( 1, 0), texelSize).gr;
//		vec2 cc = mad(vec2(2.0, 2.0), c.xz, c.yw);
//
//		// Remove the crossing edge if we didn't found the end of the line:
//		SMAAMovc(bvec2(step(0.9, d.zw)), cc, vec2(0.0, 0.0));
//
//		// Fetch the areas for this line:
//		weights += SMAAAreaDiag(areaTex, d.xy, cc, subsampleIndices.w).gr;
//	}
//
//	return weights;
//}
//
//// This allows to determine how much length should we add in the last step
//// of the searches. It takes the bilinearly interpolated edge
//// and adds 0, 1 or 2, depending on which edges and
//// crossing edges are active.
//float SMAASearchLength(sampler2D searchTex, vec2 e, float offset) {
//	// The texture is flipped vertically, with left and right cases taking half
//	// of the space horizontally:
//	vec2 scale = SMAA_SEARCHTEX_SIZE * vec2(0.5, -1.0);
//	vec2 bias = SMAA_SEARCHTEX_SIZE * vec2(offset, 1.0);
//
//	// Scale and bias to access texel centers:
//	scale += vec2(-1.0,  1.0);
//	bias  += vec2( 0.5, -0.5);
//
//	// Convert from pixel coordinates to texcoords:
//	// (We use SMAA_SEARCHTEX_PACKED_SIZE because the texture is cropped)
//	scale *= 1.0 / SMAA_SEARCHTEX_PACKED_SIZE;
//	bias *= 1.0 / SMAA_SEARCHTEX_PACKED_SIZE;
//
//	// Lookup the search texture:
//	return texture(searchTex, mad(scale, e, bias)).r;
//}
//
//// Horizontal/vertical search functions for the 2nd pass.
//float SMAASearchXLeft(sampler2D edgesTex, sampler2D searchTex, vec2 texcoord, float end, vec2 texelSize) {
//	vec2 e = vec2(0.0, 1.0);
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(texcoord.x > end && e.g > 0.8281 && e.r == 0.0)) break;
//		e = texture(edgesTex, texcoord).rg;
//		texcoord = mad(-vec2(2.0, 0.0), texelSize, texcoord);
//	}
//
//	float offset = mad(-(255.0 / 127.0), SMAASearchLength(searchTex, e, 0.0), 3.25);
//	return mad(texelSize.x, offset, texcoord.x);
//}
//
//
//float SMAASearchXRight(sampler2D edgesTex, sampler2D searchTex, vec2 texcoord, float end, vec2 texelSize) {
//	vec2 e = vec2(0.0, 1.0);
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(texcoord.x < end && e.g > 0.8281 && e.r == 0.0)) break;
//		e = texture(edgesTex, texcoord).rg;
//		texcoord = mad(vec2(2.0, 0.0), texelSize, texcoord);
//	}
//
//	float offset = mad(-(255.0 / 127.0), SMAASearchLength(searchTex, e, 0.5), 3.25);
//	return mad(-texelSize.x, offset, texcoord.x);
//}
//
//float SMAASearchYUp(sampler2D edgesTex, sampler2D searchTex, vec2 texcoord, float end, vec2 texelSize) {
//	vec2 e = vec2(1.0, 0.0);
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(texcoord.y > end && e.r > 0.8281 && e.g == 0.0)) break;
//		e = texture(edgesTex, texcoord).rg;
//		texcoord = mad(-vec2(0.0, 2.0), texelSize, texcoord);
//	}
//	float offset = mad(-(255.0 / 127.0), SMAASearchLength(searchTex, e.gr, 0.0), 3.25);
//	return mad(texelSize.y, offset, texcoord.y);
//}
//
//float SMAASearchYDown(sampler2D edgesTex, sampler2D searchTex, vec2 texcoord, float end, vec2 texelSize) {
//	vec2 e = vec2(1.0, 0.0);
//	for (int i = 0; i < SMAA_MAX_SEARCH_STEPS; i++) {
//		if (!(texcoord.y < end && e.r > 0.8281 && e.g == 0.0)) break;
//		e = texture(edgesTex, texcoord).rg;
//		texcoord = mad(vec2(0.0, 2.0), texelSize, texcoord);
//	}
//	float offset = mad(-(255.0 / 127.0), SMAASearchLength(searchTex, e.gr, 0.5), 3.25);
//	return mad(-texelSize.y, offset, texcoord.y);
//}
//
//// Ok, we have the distance and both crossing edges. So, what are the areas
//// at each side of current edge?
//vec2 SMAAArea(sampler2D areaTex, vec2 dist, float e1, float e2, float offset) {
//   // Rounding prevents precision errors of bilinear filtering:
//   vec2 texcoord = mad(vec2(SMAA_AREATEX_MAX_DISTANCE, SMAA_AREATEX_MAX_DISTANCE), round(4.0 * vec2(e1, e2)), dist);
//
//   // We do a scale and bias for mapping to texel space:
//   texcoord = mad(SMAA_AREATEX_PIXEL_SIZE, texcoord, 0.5 * SMAA_AREATEX_PIXEL_SIZE);
//
//   // Move to proper place, according to the subpixel offset:
//   texcoord.y = mad(SMAA_AREATEX_SUBTEX_SIZE, offset, texcoord.y);
//
//   // Do it!
//   return texture(areaTex, texcoord).rg;
//}
//
//// Corner Detection Functions
//void SMAADetectHorizontalCornerPattern(sampler2D edgesTex, inout vec2 weights, vec4 texcoord, vec2 d, vec2 texelSize) {
//	vec2 leftRight = step(d.xy, d.yx);
//	vec2 rounding = (1.0 - SMAA_CORNER_ROUNDING_NORM) * leftRight;
//
//	rounding /= leftRight.x + leftRight.y; // Reduce blending for pixels in the center of a line.
//
//	vec2 factor = vec2(1.0, 1.0);
//	factor.x -= rounding.x * SMAASampleLevelZeroOffset(edgesTex, texcoord.xy, vec2(0,  1), texelSize).r;
//	factor.x -= rounding.y * SMAASampleLevelZeroOffset(edgesTex, texcoord.zw, vec2(1,  1), texelSize).r;
//	factor.y -= rounding.x * SMAASampleLevelZeroOffset(edgesTex, texcoord.xy, vec2(0, -2), texelSize).r;
//	factor.y -= rounding.y * SMAASampleLevelZeroOffset(edgesTex, texcoord.zw, vec2(1, -2), texelSize).r;
//
//	weights *= clamp(factor, 0.0, 1.0);
//}
//
//void SMAADetectVerticalCornerPattern(sampler2D edgesTex, inout vec2 weights, vec4 texcoord, vec2 d, vec2 texelSize) {
//	vec2 leftRight = step(d.xy, d.yx);
//	vec2 rounding = (1.0 - SMAA_CORNER_ROUNDING_NORM) * leftRight;
//
//	rounding /= leftRight.x + leftRight.y;
//
//	vec2 factor = vec2(1.0, 1.0);
//	factor.x -= rounding.x * SMAASampleLevelZeroOffset(edgesTex, texcoord.xy, vec2( 1, 0), texelSize).g;
//	factor.x -= rounding.y * SMAASampleLevelZeroOffset(edgesTex, texcoord.zw, vec2( 1, 1), texelSize).g;
//	factor.y -= rounding.x * SMAASampleLevelZeroOffset(edgesTex, texcoord.xy, vec2(-2, 0), texelSize).g;
//	factor.y -= rounding.y * SMAASampleLevelZeroOffset(edgesTex, texcoord.zw, vec2(-2, 1), texelSize).g;
//
//	weights *= saturate(factor);
//}
//
//void main() {
//	ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
//
//	SceneData scene = getSceneData();
//	ivec2 viewportSize = ivec2(scene.displayExtentSize.xy);
//	if (pix.x >= viewportSize.x || pix.y >= viewportSize.y) return;
//
//	vec2 texelSize = scene.displayPixelSizes.xy;
//	vec2 uv = (vec2(pix) + 0.5) * texelSize;
//	vec2 pixCoord = uv * vec2(viewportSize);
//
//	vec4 uvxyxy = vec4(uv, uv);
//	vec4 texel = vec4(texelSize, texelSize);
//	vec4 offset0 = mad(texel, vec4(-0.25, -0.125,  1.25, -0.125), uvxyxy);
//	vec4 offset1 = mad(texel, vec4(-0.125, -0.25, -0.125,  1.25), uvxyxy);
//
//	vec4 offset2 = mad(
//		vec4(texelSize.x, texelSize.x, texelSize.y, texelSize.y),
//		vec4(-2.0, 2.0, -2.0, 2.0) * float(SMAA_MAX_SEARCH_STEPS),
//		vec4(offset0.xz, offset1.yw)
//	);
//
//	vec4 subsampleIndices = vec4(0.0);
//	vec4 weights = vec4(0.0);
//	vec2 edges = texture(inSmaaEdges, uv).rg;
//
//	if (edges.g > 0.0) { // Edge at north
//		weights.rg = SMAACalculateDiagWeights(inSmaaEdges, TEX2D(pc.areaTexID), uv, edges, texelSize, subsampleIndices);
//		if (weights.r == -weights.g) {
//			vec2 d;
//
//			// Find the distance to the left:
//			vec3 coords;
//			coords.x = SMAASearchXLeft(inSmaaEdges, TEX2D(pc.searchTexID), offset0.xy, offset2.x, texelSize);
//			coords.y = offset1.y;
//			d.x = coords.x;
//
//			// Now fetch the left crossing edges, two at a time using bilinear filtering.
//			float e1 = texture(inSmaaEdges, coords.xy).r;
//
//			// Find the distance to the right:
//			coords.z = SMAASearchXRight(inSmaaEdges, TEX2D(pc.searchTexID), offset0.zw, offset2.y, texelSize);
//			d.y = coords.z;
//
//			// We want the distances to be in pixel units (doing this here allow to
//			// better interleave arithmetic and memory accesses):
//			d = abs(round(mad(vec2(float(viewportSize.x)), d, vec2(-pixCoord.x))));
//
//			// SMAAArea below needs a sqrt, as the areas texture is compressed
//			// quadratically:
//			vec2 sqrt_d = sqrt(d);
//
//			// Fetch the right corrsing edges:
//			float e2 = SMAASampleLevelZeroOffset(inSmaaEdges, coords.zy, vec2(1, 0), texelSize).r;
//
//			// Ok, we know how this pattern looks like, now it is time for getting
//			// the actual area:
//			weights.rg = SMAAArea(TEX2D(pc.areaTexID), sqrt_d, e1, e2, subsampleIndices.y);
//
//			// Fix corners:
//			coords.y = uv.y;
//			SMAADetectHorizontalCornerPattern(inSmaaEdges, weights.rg, coords.xyzy, d, texelSize);
//		}
//	}
//
//	if (edges.r > 0.0) { // Edge at west
//		vec2 d;
//
//		// Find the distance to the top:
//		vec3 coords;
//		coords.y = SMAASearchYUp(inSmaaEdges, TEX2D(pc.searchTexID), offset1.xy, offset2.z, texelSize);
//		coords.x = offset0.x;
//		d.x = coords.y;
//
//		// Fetch the top crossing edges:
//		float e1 = texture(inSmaaEdges, coords.xy).g;
//
//		// Find the distance to the bottom:
//		coords.z = SMAASearchYDown(inSmaaEdges, TEX2D(pc.searchTexID), offset1.zw, offset2.w, texelSize);
//		d.y = coords.z;
//
//		// We want the distances to be in pixel units:
//		d = abs(round(mad(vec2(float(viewportSize.y)), d, vec2(-pixCoord.y))));
//
//		// SMAAArea below needs a sqrt, as the areas texture is compressed
//		// quadratically:
//		vec2 sqrt_d = sqrt(d);
//
//		// Fetch the bottom crossing edges:
//		float e2 = SMAASampleLevelZeroOffset(inSmaaEdges, coords.xz, vec2(0, 1), texelSize).g;
//
//		// Get the area for this direction:
//		weights.ba = SMAAArea(TEX2D(pc.areaTexID), sqrt_d, e1, e2, subsampleIndices.x);
//
//		// Fix corners:
//		coords.x = uv.x;
//		SMAADetectVerticalCornerPattern(inSmaaEdges, weights.ba, coords.xyxz, d, texelSize);
//	}
//
//	imageStore(outWeights, pix, weights);
//}
//
