//#version 460
//
//#extension GL_ARB_separate_shader_objects : require
//#extension GL_GOOGLE_include_directive : require
//
//#include "../include/common.glsl"
//// smaa implementation mine is based off
//// https://github.com/dmnsgn/glsl-smaa/tree/main?tab=readme-ov-file
//// https://github.com/iryoku/smaa
//
//layout(local_size_x = 16, local_size_y = 16) in;
//
//const float SMAA_PREDICATION_THRESHOLD = 0.01;
//const float SMAA_PREDICATION_STRENGTH = 0.4;
//const float SMAA_LOCAL_CONTRAST_ADAPTATION_FACTOR = 2.0;
//
//layout(set = PUSH_SET, binding = PUSH_BINDING_READ_1) uniform sampler2D inTonemap;
//layout(set = PUSH_SET, binding = PUSH_BINDING_READ_2) uniform sampler2D inDepth;
//layout(set = PUSH_SET, binding = PUSH_BINDING_WRITE_1) writeonly uniform image2D outEdges;
//
//float luma(vec3 colorLinear) {
//	return dot(colorLinear, vec3(0.2126, 0.7152, 0.0722));
//}
//
//vec2 SMAACalculatePredicatedThreshold(vec2 uv, vec4 offset0, float centerLuma) {
//	float depthCenter = texture(inDepth, uv).r;
//	float depthLeft = texture(inDepth, offset0.xy).r;
//	float depthTop = texture(inDepth, offset0.zw).r;
//
//	vec2 delta = abs(vec2(depthCenter) - vec2(depthLeft, depthTop));
//	vec2 edges = step(SMAA_PREDICATION_THRESHOLD, delta);
//
//	// lower threshold in dark areas, keep normal in bright areas
//	const float lowThreshold  = 0.01;
//	const float highThreshold = 0.02;
//	float t = clamp(centerLuma * 2.0, 0.0, 1.0);
//	float threshold = mix(lowThreshold, highThreshold, t);
//
//	return threshold * (1.0 - SMAA_PREDICATION_STRENGTH * edges);
//}
//
//void main() {
//	ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
//
//	SceneData scene = getSceneData();
//	ivec2 viewportSize = ivec2(scene.displayExtentSize.xy);
//	if (pix.x >= viewportSize.x || pix.y >= viewportSize.y) return;
//
//	vec2 texelSize = scene.displayPixelSizes.xy;
//	vec2 uv = (vec2(pix) + 0.5) * texelSize;
//
//	vec4 uvxyxy = vec4(uv, uv);
//	vec4 texel = vec4(texelSize, texelSize);
//	vec4 offset0 = mad(texel, vec4(-1.0, 0.0, 0.0, -1.0), uvxyxy); // left, top
//	vec4 offset1 = mad(texel, vec4( 1.0, 0.0, 0.0,  1.0), uvxyxy); // right, bottom
//	vec4 offset2 = mad(texel, vec4(-2.0, 0.0, 0.0, -2.0), uvxyxy); // left-left, top-top
//
//	// Luma edge detection with depth predication
//
//	float centerLuma = luma(texture(inTonemap, uv).rgb);
//	float leftLuma = luma(texture(inTonemap, offset0.xy).rgb);
//	float topLuma = luma(texture(inTonemap, offset0.zw).rgb);
//
//	vec2 deltaDirect = abs(centerLuma - vec2(leftLuma, topLuma));
//
//	vec2 threshold = SMAACalculatePredicatedThreshold(uv, offset0, centerLuma);
//
//	vec2 edges = step(threshold, deltaDirect);
//	// Early out if no edges:
//	if (dot(edges, vec2(1.0)) == 0.0) {
//		imageStore(outEdges, pix, vec4(0.0));
//		return;
//	}
//
//	// Calculate right and bottom deltas:
//	float rightLuma = luma(texture(inTonemap, offset1.xy).rgb);
//	float bottomLuma = luma(texture(inTonemap, offset1.zw).rgb);
//	vec2 deltaRB = abs(centerLuma - vec2(rightLuma, bottomLuma));
//
//	// Calculate the maximum delta in the direct neighborhood:
//	vec2 maxDelta = max(deltaDirect, deltaRB);
//
//	// Calculate left-left and top-top deltas:
//	float leftLeftLuma = luma(texture(inTonemap, offset2.xy).rgb);
//	float topTopLuma = luma(texture(inTonemap, offset2.zw).rgb);
//	vec2 deltaLLTT = abs(vec2(leftLuma, topLuma) - vec2(leftLeftLuma, topTopLuma));
//
//	// Calculate the final maximum delta:
//	maxDelta = max(maxDelta, deltaLLTT);
//	float finalDelta = max(maxDelta.x, maxDelta.y);
//
//	// Local contrast adaptation:
//	edges *= step(finalDelta, SMAA_LOCAL_CONTRAST_ADAPTATION_FACTOR * deltaDirect);
//
//	imageStore(outEdges, pix, vec4(edges, 0.0, 0.0));
//}
//
